### ISSUE TITLE
name 'dpo_inputs' is not defined

### ISSUE THREAD

**Issue by Mint-hfut** [au-revoir/model-editing-ft#4]
Traceback (most recent call last):
  File "/root/work/GC/model-editing-ft/run.py", line 89, in <module>
    main(args)
  File "/root/work/GC/model-editing-ft/run.py", line 68, in main
    trainer.train()
  File "/root/work/GC/model-editing-ft/ke/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/root/work/GC/model-editing-ft/ke/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/work/GC/model-editing-ft/ke/lib/python3.10/site-packages/transformers/trainer.py", line 3138, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/work/GC/model-editing-ft/trainer.py", line 420, in compute_loss
    loss_dpo, metrics = self.get_batch_metrics(model, dpo_inputs, train_eval="train")
NameError: name 'dpo_inputs' is not defined

**Comment by Mint-hfut** [comment]
I fixed the problem by replacing dpo_inputs with inputs
